---
title: "Mariana Arboleda's Resume"
author: Mariana Arboleda
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'dd_resume.css', 'resume']
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

source("cv_printing_functions.r")


# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1nKSghH459vR8XqTpoaeLyIDUu1N9X5Q2aTX8JzpvDi8",
  pdf_mode = params$pdf_mode,
  resume_mode = TRUE
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================


```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```



```{r}
if(params$pdf_mode){
  cat("View this resume online with links at [resume](_marianaarboleda.github.io/cv/resume/resume.html_)")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/marianaarboleda/cv/raw/main/mariana_resume.pdf)")
}
```


For a longer form version, see my [CV](https://marianaarboleda.github.io/cv/cv.html).

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV |> print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------
<!-- 
Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [https://github.com/marianaarboleda/cv](https://github.com/marianaarboleda/cv). -->

Last updated on `r Sys.Date()`.



Main
================================================================================

Mariana Arboleda {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV <- print_text_block(CV, "intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'education')
```



Selected Projects {data-icon=chart-line data-concise=true}
--------------------------------------------------------------------------------


```{r}
CV <- print_section(CV, 'projects')
```


Selected Teaching Experience {data-icon=suitcase data-concise=true}
--------------------------------------------------------------------------------


```{r}
CV <- print_section(CV, 'teaching_positions')
```

Selected Publications, Posters, and Talks {data-icon=book data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'academic_articles')
```

Selected Awards, Fellowships, & Grants {data-icon=medal data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'awards')
```


```{r}
print_links(CV)
```

